const initialData = {
    truths: [
        { id: 1, text: "你上次撒谎是什么时候？", difficulty: 1 },
        { id: 2, text: "你最尴尬的经历是什么？", difficulty: 3 },
        { id: 3, text: "你有没有做过弊？", difficulty: 2 },
        { id: 4, text: "分享一个你的秘密。", difficulty: 5 },
        { id: 5, text: "你上一次哭是什么时候，为什么？", difficulty: 4 },
        { id: 6, text: "你生命中最想感谢的人是谁？", difficulty: 1 },
        { id: 7, text: "如果可以回到过去，你会改变什么？", difficulty: 4 },
        { id: 8, text: "给我们讲一个你童年的糗事。", difficulty: 3 },
        { id: 9, text: "你手机里最近一张自拍是什么样的？", difficulty: 2 },
        { id: 10, text: "描述一下你的理想伴侣。", difficulty: 2 },
        { id: 11, text: "你收到的最奇怪的礼物是什么？", difficulty: 3 },
        { id: 12, text: "让你感觉最骄傲的成就是什么？", difficulty: 1 },
        { id: 13, text: "如果你有超能力，你希望是什么？", difficulty: 1 },
        { id: 14, text: "在你的一生中，你说的最狠的话是什么？", difficulty: 5 },
        { id: 15, text: "你最害怕什么？", difficulty: 4 },
        { id: 16, text: "如果你可以和任何人交换一天人生，你会选择谁？", difficulty: 3 },
        { id: 17, text: "在场的哪位是你最想吐槽的？", difficulty: 6 },
        { id: 18, text: "讲述一件你做过的最疯狂的事情。", difficulty: 6 },
    ],
    dares: [
        { id: 1, text: "模仿一种动物叫声。", difficulty: 1 },
        { id: 2, text: "用屁股写出自己的名字。", difficulty: 3 },
        { id: 3, text: "给你的微信第一个好友发消息说“我爱你”。", difficulty: 5 },
        { id: 4, text: "跳一段最近流行的舞蹈。", difficulty: 2 },
        { id: 5, text: "闭眼，让右边的人在你脸上画画。", difficulty: 4 },
        { id: 6, text: "在朋友圈发一张你最丑的照片。", difficulty: 6 },
        { id: 7, text: "唱一首你最拿手的歌。", difficulty: 1 },
        { id: 8, text: "抱着在场的一位异性，持续30秒。", difficulty: 4 },
        { id: 9, text: "做10个俯卧撑。", difficulty: 2 },
        { id: 10, text: "对窗外大喊“我失恋了！”", difficulty: 3 },
        { id: 11, text: "原地转十圈，然后走直线。", difficulty: 2 },
        { id: 12, text: "分享手机相册里最新的一张照片。", difficulty: 4 },
        { id: 13, text: "给手机通讯录里的第十个人打电话。", difficulty: 5 },
        { id: 14, text: "用夸张的表情朗读一段绕口令。", difficulty: 3 },
        { id: 15, text: "让在场的每个人都捏一下你的脸。", difficulty: 4 },
        { id: 16, text: "对在场的某位异性说一段深情告白。", difficulty: 6 },
        { id: 17, text: "学一段大猩猩走路的样子。", difficulty: 1 },
        { id: 18, text: "亲吻离你最近的一位同性的额头。", difficulty: 5 },
    ]
}; 